[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"