[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_ENV = "production"

[functions]
  directory = "app/api"
  directory = "app/lib"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    